---
- name: download tj/n
  git: repo=https://github.com/tj/n dest={{ dna_lib_path }}/n
- name: install Node version management
  shell: PREFIX={{ dna_home }} make install
  args:
    chdir: "{{ dna_lib_path }}/n"

# ---
# --- Python virtualenv
# ---
#
# NOTE should we use `pip --user` ?

# https://github.com/yyuu/pyenv
- name: install pyenv and essential plugins
  shell: curl https://pyenv.run | PYENV_ROOT="{{ dna_lib_path }}/pyenv" bash
  when: dev.python_pm == "pyenv"

# http://virtualenvwrapper.readthedocs.io/en/latest/
- name: install virtualenvwrapper
  pip: name=virtualenvwrapper version=4.7.2
  when: dev.python_pm == "virtualenv"

# TODO template minconda platform/version ?
- name: download miniconda
  get_url:
    url: 'https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh'
    dest: '/tmp/bootsrap-miniconda.sh'
  when: dev.python_pm == "miniconda"
# TODO when file exists + use prefix directory
- name: install miniconda
  shell: bash /tmp/bootstrap-miniconda.sh -b -f p {{ dev.python_pm_home }}
  when: dev.python_pm == "miniconda"