---
- name: check if homebrew is installed
  command: which brew
  register: is_installed
  failed_when: is_installed.rc > 1
  changed_when: no

- name: install homebrew
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  become: yes
  when: is_installed.rc != 0

- name: Ensure homebrew packages are installed.
  homebrew: name={{ item }} state=present
  with_items: "{{ homebrew_pkgs }} "

- name: Ensure homebrew casks packages are installed.
  homebrew_cask: name={{ item }} state=present
  with_items: "{{ homebrew_casks }} "
  when: homebrew_cask_enabled
  ignore_errors: True
