---
# NOTE use ansible `before` hook in site.yml ?
- name: create dotfiles head quarters
  file: path={{ dna_home }} state=directory
- file: path={{ dna_home }}/bin state=directory
- file: path={{ dna_home }}/lib state=directory
- file: path={{ dev.path }}/.psql_history state=directory recursive=true

# ---
# --- Configure zsh
# ---

- name: Set zsh as default shell
  command: chsh -s /bin/zsh {{ lookup('env', 'USER') }}

- name: install antigen framework
  get_url:
    url=https://cdn.rawgit.com/zsh-users/antigen/v1.4.0/bin/antigen.zsh
    dest={{ dna_home }}/antigen.zsh

# ---
# --- Customize shell experience
# ---

# TODO copy zshrc in dna_home and symlink it in $HOME
- name: copy shell configurations
  template: src=./templates/zshrc.j2 dest={{ ansible_env.HOME }}/.zshrc
- template: src=./templates/settings.j2 dest={{ dna_home }}/settings.zsh
- template: src=./templates/plugins.j2 dest={{ dna_home }}/plugins.zsh
- template: src=./templates/shellrc.j2 dest={{ dna_home }}/shellrc
- template: src=./templates/gitconfig.j2 dest={{ ansible_env.HOME }}/.gitconfig
- template: src=./templates/npmrc.j2 dest={{ ansible_env.HOME }}/.npmrc
- copy: src=./files/aliases.sh dest={{ dna_lib_path }}/aliases
- copy: src=./files/functions.sh dest={{ dna_lib_path }}/functions
- copy: src=./files/gitignore dest={{ ansible_env.HOME }}/.gitignore

- name: copy scripts
  copy: src={{ item }} dest={{ dna_bin_path }}
  with_fileglob:
    - ../files/scripts/*

# ---
# --- Configure tmux
# ---

- name: copy tmux configuration
  template: src=./templates/tmux.mac.j2 dest={{ ansible_env.HOME }}/.tmux.conf

- name: download Tmux Plugin Manager
  git:
    repo=https://github.com/tmux-plugins/tpm
    dest="{{ ansible_env.HOME }}/.tmux/plugins/tpm"
    version="{{ dev.tpm_version }}"

- name: copy custom psqlrc
  copy: src=./files/psqlrc dest={{ ansible_env.HOME }}/.psqlrc

# ---
# --- Install shell tools
# ---

# NOTE alternative : https://github.com/tldr-pages/tldr
- name: copy cheatsheets
  copy: src={{ item }} dest={{ ansible_env.HOME }}/.cheat/
  with_fileglob:
    - ../files/cheatsheets/*
