---
# https://github.com/qw3rtman/gg
# FIXME needs password
#- name: install Git Goodies
#  shell: curl -fsSL git.io/gg.sh | bash

# less attractive than https://github.com/ogham/exa
# https://github.com/rimraf/k
#- name: install k, the new l, yo
#  get_url: >
#    url=https://raw.githubusercontent.com/rimraf/k/master/k.sh
#    dest={{ dna_lib_path }}/k.sh

# https://github.com/rupa/z
- name: install z, the new j, yo
  get_url: >
    url=https://raw.githubusercontent.com/rupa/z/master/z.sh
    dest={{ dna_lib_path }}/z.sh
  when: tools.z

# NOTE what about percol ? (https://github.com/mooz/percol)
# https://github.com/peco/peco
- name: download peco, Simplistic interactive filtering tool
  get_url: >
    url=https://github.com/peco/peco/releases/download/v0.3.3/peco_darwin_amd64.zip
    dest={{ tmp_path }}/peco.zip
  when: tools.peco
- unarchive: src={{ tmp_path }}/peco.zip dest={{ tmp_path }} copy=no
  when: tools.peco
- command: mv {{ tmp_path }}/peco_darwin_amd64/peco {{ dna_bin_path }}/peco
  when: tools.peco

- name: install autoenv, Directory-based environments
  git: >
    repo="https://github.com/kennethreitz/autoenv"
    dest={{ dna_lib_path }}/autoenv
  when: tools.autoenv

# https://github.com/junegunn/fzf
- name: install fzf, fuzzy searcher
  git: repo=https://github.com/junegunn/fzf dest={{ dna_lib_path }}/fzf
  when: tools.fzf
- command: "{{ dna_lib_path }}/fzf/install"
  when: tools.fzf

# http://www.jefftk.com/icdiff
# configure git to use it: https://github.com/jeffkaufman/icdiff/tree/release-2.0.4#using-with-git
- name: install icdiff
  get_url: >
    url=https://raw.githubusercontent.com/jeffkaufman/icdiff/release-{{ tools.icdiff }}/icdiff
    dest={{ dna_bin_path }}/icdiff
    mode="ugo+rx"
  when: tools.icdiff

# TODO: run `joe u`, needs to be allowed on OSX
# TODO: platform detection
- name: install joe
  get_url: >
    url=https://github.com/karan/joe/releases/download/{{ tools.joe }}/joe-darwin
    dest={{ dna_bin_path }}/joe
    mode="ugo+rx"
  when: tools.joe