---
# NOTE Alternative : brew install macvim --HEAD --with-cscope --with-lua --override-system-vim --with-luajit --with-python
# TODO execute when editor.version >= 7.4 and the one installed is not
# FIXME lua version (see path) is hardcoded
# download and compile vim from source
- name: download latest vim
  git: repo=https://github.com/vim/vim
       dest={{ dna_lib_path }}/vim
  when: editor.name == "vim"

# custom ruby path bypass rbenv issues
- name: compile and install vim
  shell: >
    ./configure
    --with-features=huge
    --enable-multibyte
    --enable-rubyinterp
    --with-ruby-command=/usr/bin/ruby
    --enable-pythoninterp
    --with-python-config-dir=/usr/lib/python2.7/config
    --enable-perlinterp
    --enable-luainterp
    --enable-cscope
    --enable-fail-if-missing
    --with-lua-prefix={% if ansible_os_family == 'Darwin' %}/usr/local/Cellar/lua/5.2.4_4{% else %}/usr{% endif %}
  args:
    chdir: "{{ dna_lib_path }}/vim"
  when: editor.name == "vim"
- shell: make VIMRUNTIMEDIR=/usr/local/share/vim/vim80/
  args:
    chdir: "{{ dna_lib_path }}/vim"
  when: editor.name == "vim"
- shell: make install
  become_user: root
  become: true
  args:
    chdir: "{{ dna_lib_path }}/vim"
  when: editor.name == "vim"

- name: install Vim-plug, Minimalist Vim Plugin Manager
  file: path={{ ansible_env.HOME }}/.vim/autoload state=directory
- file: path={{ ansible_env.HOME }}/.vim/plugins/settings state=directory recurse=yes
- get_url:
    url=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest={{ ansible_env.HOME }}/.vim/autoload

- name: Copy vimrc configuration file
  template: src=./templates/vimrc.j2 dest={{ ansible_env.HOME }}/.vimrc

- file: path={{ editor.rcpath }}/plugins/settings state=directory
- name: copy vim partials configuration
  template: >
    src={{ item }}
    dest={{ editor.rcpath }}/plugins/
  with_fileglob:
    - ../templates/vimrc-partials/*.vim

- name: copy vim plugins settings
  template: >
    src={{ item }}
    dest={{ editor.rcpath }}/plugins/settings/
  with_fileglob:
    - ../templates/vimrc-partials/settings/*.vim

- name: create neovim configuration directory
  file: path={{ ansible_env.HOME }}/.config/nvim state=directory
  when: editor.name == "nvim"
- name: copy vim to neovim configuration hook
  copy: src=./files/vim-to-neovim.vim dest={{ ansible_env.HOME }}/.config/nvim
  when: editor.name == "nvim"

# FIXME: Hang - name: download and install plugins
#  shell: /usr/local/bin/vim +PlugInstall +qall

# TODO: download man page (but where to put it on mac ?)
# TODO: is it the right mode for user execution ?
- name: install v, z for vim
  get_url:
    url=https://raw.githubusercontent.com/rupa/v/master/v
    dest={{ dna_bin_path }}/v
    mode=0755
