---
author:
  name: Xavier Bruhiere
  mail: xavier.bruhiere@gmail.com

git:
  username: Xavier Bruhiere
  mail: xavier.bruhiere@gmail.com

# zsh configuration
# https://github.com/unixorn/awesome-zsh-plugins
prompt_theme: robbyrussell
# antigen theme agnoster
# others i like: kennethreitz mrtazz sorin theunraveler

# some environments exercise tight control over what 3rd party apps can be installed
homebrew_cask_enabled: false

dev:
  path: "{{ ansible_env.HOME }}/Hack"
  tpm_version: 693e5a2a0f6acfd2666882655d5dfd32e8c6c50b

  ruby_version: 3.0.2

  python_versions:
    - 3.9.6
    - 2.7.10
  node_version: stable
  # FIXME we need go to build go > 1.5+ : https://github.com/moovweb/gvm/issues/161
  go_version: 1.4
  go_path: "{{ ansible_env.HOME }}/Hack/go"
  # support virtualenv, pyenv and miniconda
  python_pm: pyenv
  python_pm_home: "{{ ansible_env.HOME }}/.virtualenvs"

editor:
  rcpath: "{{ dna_lib_path }}/vimrc"
  name: nvim
  tab: 2
  leader: " "
  colorscheme: nord
